### ISSUE TITLE
ERROR - Failed to process PARTIAL REPAYMENT proxy box for transaction id

### ISSUE THREAD

**Issue by TheStophe** [duckpools/off-chain-bot#6]
Saw this in the logs a few times today. Looks like the code may need more graceful handling of partial repayments...

```
s
Jan 30 20:35:56 cwatts python3[1676876]: INFO - Starting SUSD request processing
Jan 30 20:35:56 cwatts python3[1676876]: INFO - Found: 0 boxes
Jan 30 20:35:57 cwatts python3[1676876]: INFO - Starting PARTIAL REPAYMENT request processing
Jan 30 20:35:58 cwatts python3[1676876]: INFO - Found: 1 boxes
Jan 30 20:36:14 cwatts python3[1676876]: ERROR - Failed to process PARTIAL REPAYMENT proxy box for transaction id: 177f04b5c68ab64b4eef9d52b22d7df71d2b330900021aa3b876ef158d90fff2. Exception: 'int' object has no attribute 'text'
Jan 30 20:36:14 cwatts python3[1676876]: Traceback (most recent call last):
Jan 30 20:36:14 cwatts python3[1676876]:   File "/home/ada/ergo/duckpools/off-chain-bot/helpers/job_helpers.py", line 45, in job_processor
Jan 30 20:36:14 cwatts python3[1676876]:     proxy_job(pool, box, processed_tx_obj)
Jan 30 20:36:14 cwatts python3[1676876]:   File "/home/ada/ergo/duckpools/off-chain-bot/erg_pool/e_partial_repay_proxy.py", line 109, in process_repay_partial_proxy_box
Jan 30 20:36:14 cwatts python3[1676876]:     [box_id_to_binary(box["boxId"]), box_id_to_binary(collateral_box)],
Jan 30 20:36:14 cwatts python3[1676876]:                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 30 20:36:14 cwatts python3[1676876]:   File "/home/ada/ergo/duckpools/off-chain-bot/helpers/node_calls.py", line 25, in box_id_to_binary
Jan 30 20:36:14 cwatts python3[1676876]:     return json.loads(get_request(node_url + "/utxo/withPool/byIdBinary/" + box_id).text)["bytes"]
Jan 30 20:36:14 cwatts python3[1676876]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 30 20:36:14 cwatts python3[1676876]: AttributeError: 'int' object has no attribute 'text'
Jan 30 20:36:15 cwatts python3[1676876]: INFO - Starting liquidation request processing
Jan 30 20:36:16 cwatts python3[1676876]: INFO - Found: 9 boxes
Jan 30 20:36:55 cwatts python3[1676876]: INFO - Starting Interest Rate Job

```

**Comment by sb01101001** [comment]
Addresse

**Comment by sb01101001** [comment]
Addressed with commit https://github.com/duckpools/off-chain-bot/commit/d677150367d2d7879e872d24f473f7c31f463e86
handled as is handled in token pools.

**Comment by TheStophe** [comment]
From ChatGPT help, I was also looking at adding extra error handling in https://github.com/duckpools/off-chain-bot/blob/d677150367d2d7879e872d24f473f7c31f463e86/helpers/node_calls.py#L24

helpers/node_calls.py function box_id_to_binary

Up to you.

```
def box_id_to_binary(box_id):
    try:
        response = get_request(node_url + "/utxo/withPool/byIdBinary/" + box_id)
        if response.status_code == 200:
            data = json.loads(response.text)
            # Ergo-specific handling, assuming 'bytes' is the key for the data you need
            if "bytes" in data:
                return data["bytes"]
            else:
                # Handle case where 'bytes' key is missing or different
                raise ValueError("Missing 'bytes' key in response data")
        else:
            # Handle non-200 responses
            raise ConnectionError(f"Failed to get data for box_id {box_id}, status code: {response.status_code}")
    except Exception as e:
        # Handle other exceptions, possibly log them for further analysis
        raise RuntimeError(f"An error occurred while processing box_id {box_id}: {str(e)}")
```
