### ISSUE TITLE
WARNING - Failed to submit transaction ... Failed txID quoted as: -1

### ISSUE THREAD

**Issue by TheStophe** [duckpools/off-chain-bot#8]
Reporting a warning from the logs that is either a raised error or could use some cleaning up to not be so verbose...Note this is from the Duck Pools 01 proposal bot update.

Below is an example, I redacted my computer user name with <user> below:

>Feb 06 20:07:11 <user> python3[3445497]: WARNING - Failed to submit transaction: {"requests": [{"address": "67d7wq2KP495sNBtVThj4m7Xf2awfow9ZhdDqM6ypU5gqfwXq2tuXVem3pSgKrGNV4zwkvG6RVFcKrHN4BGfKc5Po89vtSbfsXK53RoyNaPcXiKcjNbvbVkD5EkUgLWuFsqgb9rN3bGsufABLb6rrRF4gkXLGqeYWqykuovqakoePdG5ChfeFzqPaHkBntqZ8PknmacTuJLmJ89MBdfscQf8BZzxgMco19ehR1j8rWtTQWniXYcYzpp3B1mhiReA5kURW574vNPZWBwymLMhBudfu3jDoVeFwwGaJtehDKYdT4NfA4NNyiHyRih6yNH3P5t5PKkS5cLoq8MNJucZJydjjRxzWyk2vPLtMiT43T77gfjR8Q6eWvDwBP6TUt85G362oYSvkoSXcBjbMM7KVQsK2MkAnCGtS1m3FwCn19MhdArGquoEDs9t4XBtNMwnVQsWxd4LUeAG1vakn7XiYTsmWkVbYRNJA9m95nxteWrUEvDT4ybezsdNmqUk13s8ybiR2c67iJzUCvB7zQCQQnvpWKSgtBGboDWu79reguFEXCuBm6kJddwsAniQ7Sm3poLJw8BYBCAiEBa5or7CwF5JkfYwcRdi3CoBBwoXYf3tYUJ46S8Y3X47eNbvBx29fc5tPEQ2UsU2CwdgZzFMGZUF1hfkFLwiShmGtDvxWAPuutDonrb1uWPhrPJ7E4LAVwhBkxWksfjn3BnMaZC7hRdqLjWgmgmbzQ9kKW4bco5WVwtDx42o3S1SASLMq3uhiCjiqry8E2VtRCqg2VjwXJzbrbmrQn863Rh53TwAFFTJAiqNua6zZ73", "value": 300000, "assets": [{"tokenId": "35f826497f8eadf5b46f768485cec175c35c11360b4821ea92bbbe855777b55c", "amount": 1}], "registers": {"R4": "11a4018084af5fd48baf5fd48baf5f96c8af5f84b5af5ffe8daf5fc295af5f8696af5f9cc1af5f9cc1af5f9cc1af5f9cc1af5f829daf5f829daf5f829daf5f829daf5ff085af5fa28daf5fba89af5fba89af5fba89af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f90ebaf5f90ebaf5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5fe6e2af5fe6e2af5fe2c4af5facc0af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff698af5ff698af5ff698af5ff698af5fd08eaf5f86b3b05ff8aeb05fb88faf5f8891b05f", "R5": "05fce99101", "R6": "0402", "R7": "0101", "R8": "0101", "R9": "0101"}}, {"address": "9gZm5sHRrTmzRaFi6VXX8rsj5V4jMMqfUMJbdskeZZz37qfEscH", "value": 610000.0, "assets": [], "registers": {}}, {"address": "4FC5xSYcm6fUjNGmpQJMuVW9zU4KSa9qxg2uJwEC2x2CmmdM1fUyQ7hTs8uWrqLfSNjc4j8R", "value": 1000000, "assets": [{"tokenId": "33c1c5658e2d1648e01600d3dea3df0c7487b39ec2c76f76aa1e3b487839bef0", "amount": 1}, {"tokenId": "a60ccd7baedd6f403d3499626e4e8cc40383c6bd759fce15d3a006741ba774ba", "amount": 1}], "registers": {}}], "fee": 1290000.0, "inputsRaw": ["c0a3860110180400058084af5f04020400058080d4aff9dcfc1f0404040604f00104dc06048092f401040004000402040404060408040a04020500050a04000e2084f30401051b972faac719b3589a0978fa54a7b721c7d6b40053ba4aeefad1db04000e2038d56c0690e13d2c812daa6aeb766df571aff674a7901a7dc4817208527b191ad80fd6017ea305d602b2a5730000d603e4c672020411d604db63087202d605db6308a7d606e4c6a70411d607b17206d6087301d609db6501fed60ab27209730200d60be4c6720a0411d60cdb6308b27209730300d60d7e9973048cb2720c7305000206d60e9d9c7e720806720d9a7e8cb2720c7306000206720dd60f99e4c6720205057201d1ededededededededededed92997201e4c6a705057e73070590b17203730893c2a7c2720292c1720299c1a77e7309059372047205eded937206b47203730a7207937eb27203720700069a7e7208069a9a9a9a9a7eb2720b730b00069d9c7eb2720b730c0006720e7e7208069d9c9d9c7eb2720b730d0006720e7e720806720e7e7208069d9c9d9c9d9c7eb2720b730e0006720e7e720806720e7e720806720e7e7208069d9c9d9c9d9c9d9c7eb2720b730f0006720e7e720806720e7e720806720e7e720806720e7e7208069d9c9d9c9d9c9d9c9d9c7eb2720b73100006720e7e720806720e7e720806720e7e720806720e7e720806720e7e72080693b172039a72077311ed92720f731290720f731393e4c672020604e4c6a70604938cb2720c731400017315938cb2db6308720a731600017317edede4c672020701e4c672020801e4c67202090193b17204b17205a8f2480135f826497f8eadf5b46f768485cec175c35c11360b4821ea92bbbe855777b55c010611a3018084af5fd48baf5fd48baf5f96c8af5f84b5af5ffe8daf5fc295af5f8696af5f9cc1af5f9cc1af5f9cc1af5f9cc1af5f829daf5f829daf5f829daf5f829daf5ff085af5fa28daf5fba89af5fba89af5fba89af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fa089af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5fecb0af5f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f9ea7b05f90ebaf5f90ebaf5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5ff4b5af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5f94b3af5fe6e2af5fe6e2af5fe2c4af5facc0af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff098af5ff698af5ff698af5ff698af5ff698af5fd08eaf5f86b3b05ff8aeb05fb88faf5f05dae4910104020101010101014e2c84412b6386ef2c7aafed2a24180485e09654e48dac2b7a6636815ae767e500", "c0843d100208cd030d858d2453cb644ab0a91ce880483615a7bca0b677cf938ff8dac5adba75d57f0401ea027300d192a3730190d1480233c1c5658e2d1648e01600d3dea3df0c7487b39ec2c76f76aa1e3b487839bef001a60ccd7baedd6f403d3499626e4e8cc40383c6bd759fce15d3a006741ba774ba0100d2ed8084d1dabb219fba905941b7ab1811015c172d85a11b92ba901b45d0240d02"], "dataInputsRaw": ["80e3be0a10430400040604060480897a040004000402040204040404058080d4aff9dcfc1f058080d4aff9dcfc1f0e20eac027ed8167d565eb4b62f6b8de18ec727d9d7ccfc246f95c59ea72b9975a300607038d7ea4c6800005000501040204020400040004040480ade20404d00f04060400040004040402050105000e20241307198ce8b7f7aa222cfd45d500646c1c679080605715ca4045514ccefd0c0580c2d72f0580897a040406016404020480b518058084af5f04000e2035f826497f8eadf5b46f768485cec175c35c11360b4821ea92bbbe855777b55c04000e205ef4bc9e075f8113416ff544efeca7d397bc03e142a7c3816fc00bc494603b8504000500059480d4aff9dcfc1f059480d4aff9dcfc1f0400040204000400058088debe0104c0020580d0acf30e058088debe01049003058088debe0104c0020580d0acf30e058088debe0104f4030580d0acf30e049003058088debe0104c002050204000100d81ed601db6501fed602b17201d603b2a5730000d604db63087203d605b27204730100d6068c720502d607db6308a7d608b27207730200d6098c720802d60a9972067209d60b93c27203c2a7d60c7303d60d92c172037e720c05d60e93b27204730400b27207730500d60f8c720801d610938c720501720fd611b27204730600d612b27207730700d6139372117212d614b27204730800d615b27207730900d6168c721501d617938c7214017216d61899730a8c721402d61999730b8c721502d61a9972187219d61b730cd61c730dd61d91720a730ed61e95721d720a9c720a730f959172027310d815d61fb2a5731100d620b2db6308721f731200d6218c722002d622c1721fd623b27201731300d624db63087223d625b27224731400d626997e7222067e731506d6277ee4c67223040406d6287ec1722306d6297316d62ab27201731700d62b8cb2722473180001d62cdc0c1ae4c6722a061a02722b7319d62db2e4c6722a0411722c00d62ee4c6721f0558d62fb27201731a00d630b27201731b00d631b1e4c672300411d632e4c6721f0959d6338c723201d1edededededededededededededededededededededededed720b939c720a731c72218f720a731d720d720e72107213721793721a722193cbc2721f731e9272229a9a731f7e720c057320929d9c9c7e8c72250206722672279a9c9a72289d9c72287e73210673227e7229069c722672279d9c7e7221067e722d067e722906938c7220017216e6c6721f040e938c722e0299b1e4c6722f04117323938c722e01723193e4c6721f06598602722db2e4c6722a0711722c0093e4c6721f070e722be6c6721f0807ed9172337ea3058f72337e9aa3732405938c7232027325ed938cb2db6308722f73260001732793e4c6722f06047231938c722501720f938cb2db63087230732800017329938cb2db6308722a732a0001721bd1ecededededededed720b720d720e72137217721d72108f721a732bededededededed720b720e938c7211018c721201720d9372147215919d9c721c9a7e7206067e7218067e99732c8c721102069d9c721c9a7e7209067e7219067e99732d8c72120206721095917202732ed803d61fb2a5732f00d620b27201733000d621b2db6308721f733100ededed93c2721fe4c67220080e92c1721f7e720c05ed928c722102a29590721e73329d721e7e7333059590721e73349a9d99721e73357e7336059d73377e7338059a9a9d9999721e7339733a7e733b059d733c7e733d059d733e7e733f057340938c722101720f938cb2db6308722073410001721b7342c1f2480484f30401051b972faac719b3589a0978fa54a7b721c7d6b40053ba4aeefad1db01a8fa0b48932160bf4022dd54fe4fb3c64b233b656716c570dc048e81688e43f1a3ee9ffea5aefe0fb948c4aac0cc282da2c7ad8d66b90461da76b1d5747d2d9aa01fe6a73f889b3b88c9e9dca5aefe0fe023c5f382b6e96fbd878f6811aac73345489032157ad5affb84aefd4956c297edb38c8d05009853a8cdb0d64fae4383153ff4c15512eb33f92bf294fe08bca66f7373eb1de800", "8092f401100208cd03dda8fe44b65ff96eb9dd442e6f10aca93f7351e96f2cbb1862c21a9055bc8b9604bc0fea027300d191a37301a1cb470138d56c0690e13d2c812daa6aeb766df571aff674a7901a7dc4817208527b191a01011106f001a01f00000080b602cd55b12a3166a681aa907a65d91706861232b4a376f67bd53480034f5428f1a100"]} Failed txID quoted as: -1

**Comment by TheStophe** [comment]
Here is an updated Warning Message. This log seems like user error setting up some of their node API and password config, like the wallet is locked.

Still unclear what this warning means, and whose fault it is....

> 
> INFO - Found: 5 boxes
> Dec 03 20:28:40 <user> python3[2963465]: INFO - Starting Interest Rate Job
> Dec 03 20:28:42 <user> python3[2963465]: WARNING - Failed to submit transaction: {"requests": [{"address": "5s1ivH9pMoYPPX5YV8GZ71xNw14vbWYx5Bp1KbD3kFxPkmxMx3PQMPRF2pXMRcECbQ5bJ9J1Jaysmv1LmBC1yUM44pnLBjE8LT7Ld6Ym9VLyUAXuHvDFHvVek6gvrkbWJy8Rc6RRbx5v5x9QyiCfVquR8z7GFbbysvsvbBpJ4bM2kzY61DiQuZLB9JYNdEKAvRXazGZyr3MwqqZZYjfpBs3tJSo1haBLwxL5ZnP2fsyAaoZfB3n9xjiBv9u71ydbZ8z8D52bStnai8V5VSybLFNTYPuHFeEUSvNt689nchEmyygEH8BJfz6fXFtJZiKMbKZK2Q84hYm2QtoEqWzJBK4Pmmmjm1LM2MZ35iZKmezBoQKHmhfiL6Fxpy6ttTLbeKhFy7D7t1CZehnqf3phtnJFSuGdyN3LJkqsk1myrpRP3nH3oqcZhjY6HMYvvHea7fSpATmzMYuegQHgW33nC74jVnMd1CWdx7LRGCBWWCYHiQNxxVCvec6jdc1sZ6Wa18vBDhAtxyVsHxkQoE3DLxn66Qzv9ik8HC1wjCGq4ZSyfYWTtzKyxDiH4", "value": -630000000, "assets": [{"tokenId": "5255c5b1da74994236ee5d737516d02839f43cc6b61b206e1dc19ed39d9c11b8", "amount": 1}, {"tokenId": "13badb3b0c304a6d5859f70ac341d5b2b4ceb0be4c640ae6d1ad3a8a1edf6285", "amount": 8999999999999994}], "registers": {"R4": "11078084af5fdebdbf6088d18460ace3e15f86b19460d0c5b360faa6e75f", "R5": "0101", "R6": "0101", "R7": "0101", "R8": "0101", "R9": "0101"}}, {"address": "4T5Phw51x11bWjCaDiLUD42YvopXoVQZsbFtFPqYSTcKn1X9Q5W67xE3g1gDxWJgfRNTH3SkikZuyyq5CJEzW6qhDCYeDGDWMLbVLaE3crZjrcFxJhdJ5Ame2L63SSidJnLSgivz4vhJtMmuSpzzJVGDys2cPuDzCAfVAptjGYHeyXKu6HSeZREEvmTLBrVxiEk4xrV6p5shnFJzeHJh8HnHW97LtBFj4vmNYNZe5x9wnm2aQrr2zaQ5XuGejBm1ftUdYA8vy3EeVzYDwfkfEo8me7uyZLmm6EF7qnfsPxpSWBB8kxCfsu7ZaUxWTHMp3eNWwg3w9eeDMKUJUnqfocLgiEkaD94vxuwCaEcxxKkFu2nkfHuUU6n2aiXPcZRFNWcVyNKD8pVFMSgfxi8iKmy5WC9rhWDvr4FzK1V4ks25S1aW39BkkWmz7mamhFHKeV95cYDoSYnYpcVNgZU4u9x9mUJJY68ibejZ313bcpZ6S35vKXD8TsCmof8uJ33KnMFPsVR6Wx9Ge3QJ3VAHr6xNtP1NSnzs1prkHjXnwqWJNc39q2NAZF4TrC9SvMY4XoW5w9sp1zwXbwQAagtFRa74nCAKSCdf6WUGML1vUNUhPJECtUvfdXKC3P1D3AWPthMFQCZb4BiNjbMHCVPAKQ49GnEXy7TUVunE1UjTw2G4PXWFrP26nC6cnmHmYetyCfKZBoLY17sv84vCUcQMAiPpjQK8FdYcZLdaQezYPDcGc6CKvYwheWYvP58jaL5Nb1G5PFg62WXzjunKzNnxQV8hCAeosQw5vjTPwYCwAxNRYBtP7bN", "value": 860000000, "assets": [{"tokenId": "13badb3b0c304a6d5859f70ac341d5b2b4ceb0be4c640ae6d1ad3a8a1edf6285", "amount": 1}], "registers": {"R4": "11018084af5f", "R5": "05a086ac01", "R6": "040e", "R7": "0101", "R8": "0101", "R9": "0101"}}], "fee": 4000000, "inputsRaw": ["c0a187701012040004dc06058092f401040204020400040004020580ade204040004000502058084af5f058084af5f04dc060400058084af5f0402d80ed601b2a5730000d6029c7e7301057302d603db63087201d604db6308a7d605b27203730300d606b27204730400d6078c720601d608e4c6a70411d609b2db6501fe730500d60ae4c672090411d60be4c672010411d60cb2db63087209730600d60db2a5730700d60edb6308720dd1edededededededededededededededededed93c27201c2a792c172019999c1a77308720293b27203730900b27204730a00938c7205017207938c720502998c720602730b93b37208830105b0720a730cd9010f599d9c8c720f018c720f02730d720b93b17203b17204edededede4c672010501e4c672010601e4c672010701e4c672010801e4c672010901938c720c01720793e4c672090604b1720892b1720a730e93c2720dc2720992c1720d720293b2720e730f00720c93e4c6720d0604b1720b93e4c6720d0411830105731093e4c6720d0505e4c672090505edede4c6720d0701e4c6720d0801e4c6720d090193b1720e731185db52025255c5b1da74994236ee5d737516d02839f43cc6b61b206e1dc19ed39d9c11b80113badb3b0c304a6d5859f70ac341d5b2b4ceb0be4c640ae6d1ad3a8a1edf6285fbffe9d7bcaefe0f0611068084af5fdebdbf6088d18460ace3e15f86b19460d0c5b360010101010101010101017a1475b6cbedb1064a9648a14e20d04a8e538d68ee5fca618f0cf90bba6a084f00"], "dataInputsRaw": ["a0bdb41510170400058084af5f04020400058080d4aff9dcfc1f040404f00104dc06048092f401040004000402040404060408040a04020500050a04000e2090290924d95d699f5852d54dd5c20d01a3c729b11e7ccb5444671f62bec3b4bc04000e2054e175e1491af439c10652db7685651c7e57530d18a31c5b46e0b85f6bfb9b18d810d6017ea305d602b2a5730000d603e4c672020411d604db63087202d605db6308a7d606e4c6a70411d607b17206d6087301d609db6501fed60ab27209730200d60be4c6720a0411d60cb27209730300d60ddb6308720cd60e7e9973048cb2720d7305000206d60f9d9c7e720806720e9a7ec1720c06720ed61099e4c6720205057201d1ededededededededededed92997201e4c6a705057e73060590b17203730793c2a7c2720292c1720299c1a77e7308059372047205eded937206b4720373097207937eb27203720700069a7e7208069a9a9a9a9a7eb2720b730a00069d9c7eb2720b730b0006720f7e7208069d9c9d9c7eb2720b730c0006720f7e720806720f7e7208069d9c9d9c9d9c7eb2720b730d0006720f7e720806720f7e720806720f7e7208069d9c9d9c9d9c9d9c7eb2720b730e0006720f7e720806720f7e720806720f7e720806720f7e7208069d9c9d9c9d9c9d9c9d9c7eb2720b730f0006720f7e720806720f7e720806720f7e720806720f7e720806720f7e72080693b172039a72077310ed9272107311907210731293e4c672020604e4c6a70604938cb2720d731300017314938cb2db6308720a731500017316edede4c672020701e4c672020801e4c67202090193b17204b172058b83560113badb3b0c304a6d5859f70ac341d5b2b4ceb0be4c640ae6d1ad3a8a1edf6285010611ae038084af5fa8b4af5fa8b4af5fa8b4af5fa8b4af5fa8b4af5fa8b4af5feca5af5feca5af5feca5af5f9e9eaf5f889faf5f889faf5f889faf5f889faf5f889faf5f889faf5f889faf5f889faf5f889faf5f9e9eaf5f9e9eaf5f9e9eaf5f9e9eaf5f9e9eaf5f9e9eaf5f9e9eaf5fb89eaf5fb89eaf5fb89eaf5fb89eaf5f9099af5f9099af5f9099af5f9099af5f9099af5f9099af5f9099af5fce94af5fce94af5fce94af5fce94af5fce94af5f8a94af5fc094af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fcc95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5fce95af5f9896af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5f9295af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5fc895af5f8096af5f8096af5f8096af5f8096af5f8096af5f8096af5f8096af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f8c96af5f9297af5f9297af5f9297af5f9297af5f9297af5f9297af5f9297af5f9297af5f9297af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fc496af5fbe97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5f9e97af5fd496af5fd496af5fd496af5fd496af5fd496af5fd496af5f9296af5f9296af5f9296af5f9296af5f9296af5f9296af5f9296af5f9296af5f9296af5f9296af5fb495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5f8495af5fd692af5fbc92af5fbc92af5fbc92af5fbc92af5fbc92af5fbc92af5fbc92af5fbc92af5fe096af5fe096af5fe096af5fe096af5fe096af5fa498af5fa498af5fa498af5fa498af5fa498af5fa498af5fa498af5fa498af5fda98af5fda98af5fda98af5fda98af5fda98af5fda98af5fda98af5fda98af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fd893af5fe094af5fe094af5fcc94af5fbe94af5f8494af5f8494af5f8e99af5f9490af5f849aaf5f849aaf5f849aaf5fe894af5fe894af5fd48baf5fd48baf5fd48baf5fd48baf5fd48baf5fb48caf5fc290af5fc290af5fc290af5fc290af5fc290af5fd493af5fd493af5fe093af5fe293af5fe293af5f8e94af5ff68eaf5ff68eaf5fe08baf5f8091af5f8091af5f8091af5f8091af5fe88daf5fe88daf5fe88daf5fc090af5fc090af5fe28baf5fe28baf5fe28baf5fe08baf5fe08baf5fe08baf5fe08baf5fe08baf5fe08baf5fc090af5fc090af5fbe90af5fb490af5fb490af5fb490af5fb490af5fb490af5fb490af5fb490af5fb490af5fc890af5fe88baf5fe88baf5fc890af5fc890af5fc890af5fc890af5fc690af5fe88baf5fe88baf5fc28caf5fc28caf5fc28caf5fc28caf5fc28caf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5fe88baf5ffc8baf5ffc8baf5ffc8baf5ffc8baf5ffc8baf5ffc8baf5ffc8baf5fc08caf5f05a086ac01040c010101010101da51e1b3604176b4b300f968baaab4aa702555032f436c458b2c4c81729c657800"]} Failed txID quoted as: -1

**Comment by TheStophe** [comment]
Just an update, as of now running off-chain-bot updated, getting errors:
* WARNING - Failed to process or refund transaction object: ...  "dataInputsRaw": []} Failed Refund txID quoted as: -1

followed by
* ERROR - Failed to process repay to pool proxy box for transaction id:

```
INFO - Starting lend request processing
INFO - Found: 2 boxes
WARNING - Failed to process or refund transaction object: {"requests": [{"address": "9gSsDJixycevrHL7xxD7dr9R9G3Mi4W7LVohvK1GAjycsJc7zSy", "value": 2000000, "assets": [], "registers": {"R4": "0e206ea27d7aaec4a1a2094b7c28a474e94fea5bae420492bba12e029e7777a238bc"}}], "fee": 1000000, "inputsRaw": ["c08db701100a040604000580897a01000404040004000e20fc888e0eed50a4042324793a7894134d83c7aaf5c99f4bf643e7e2b4e71e009501000100d1d801d601e4c6a7040e958fb1a57300d802d602b2a5730100d603c67202040eededed93c2720272019099c1a7c17202730295e6720393e47203c5a77303927ea305e4c6a70605d803d602b2a5730400d603db63087202d604c67202070eeded93c2720272019591b172037305d801d605b27203730600ed938c7205017307928c720502e4c6a70505730895e6720493e47204c5a77309bcb65701089990451bb430f05a85f4ef3bcb6ebf852b3d6ee68d86d78658b9ccef20074fad8ce005040e240008cd02fdde0388f38cc75ced977fafe3c6a7bf5a513e5b1f666e60b8feed3d6b7513c705feebb80b05b4edae010e2062a9373681f650610acfff3f14ba77b6e5feadc844641f44cbbde28cbe22aa3a9246945f5c113506c8e2ef310f87192bf94696c3495aa17d69e7b79b1a57c73b00"], "dataInputsRaw": []} Failed Refund txID quoted as: -1
INFO - Starting withdrawal request processing
INFO - Found: 0 boxes
INFO - Starting borrow request processing
INFO - Found: 0 boxes
INFO - Starting repay to pool request processing
INFO - Found: 1 boxes
ERROR - Failed to process repay to pool proxy box for transaction id: 67cbdbe9a829dbe4085f5c97c25efb1a9b456785fa34decf6859dd10c7d9324e. Exception: list index out of range
Traceback (most recent call last):
  File "/home/cwatts/ergo/duckpools/off-chain-bot/helpers/job_helpers.py", line 43, in job_processor
    processed_tx_obj = proxy_job(pool, box, processed_tx_obj)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cwatts/ergo/duckpools/off-chain-bot/erg_pool/e_repay_to_pool.py", line 15, in process_repay_to_pool_box
    final_borrowed = borrowed - int(box["assets"][0]["amount"])
                                    ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
